# Generated by Django 4.2.1 on 2023-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
